# docker-compose.yml

services:
  medai-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
    command: python api.py
    networks:
      - medai-network

  medai-interface:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
    command: streamlit run interface.py --server.address 0.0.0.0
    depends_on:
      - medai-api
    networks:
      - medai-network

networks:
  medai-network:
    driver: bridge